default_stages: [commit, push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: local
    hooks:
    - id: black
      name: black
      entry: black
      language: system
      exclude: ^(venv/|docs/)
      types: ['python']

    - id: isort
      name: isort
      entry: isort
      language: system
      exclude: ^(venv/|docs/)
      types: ['python']

    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: ['python']

    - id: bandit
      name: bandit
      entry: bandit
      language: system
      args: ['-c',  'pyproject.toml']
      types: ['python']

    - id: xenon
      name: xenon
      args: [--max-absolute B --max-modules A --max-average A]
      entry: xenon
      language: python
      types: ['text']

    - id: mypy
      name: mypy
      entry: mypy
      language: system
      'types_or': [ python, pyi ]
      args: ["--no-strict-optional", "--ignore-missing-imports", "--scripts-are-modules"]
      require_serial: true
