name: Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry export -f requirements.txt --output requirements.txt --without-hashes --dev
        pip install -r requirements.txt
    - name: Analysing the code with pytest
      run: |
        pytest
